---
- debug:
    msg: 
    - "ansible_distribution:         {{ ansible_distribution }}"
    - "ansible_distribution_release: {{ ansible_distribution_release }}"
    - "ansible_distribution_version: {{ ansible_distribution_version }}"

- set_fact:
    distribution_codename: "{{ ansible_distribution|title }}-{{ ansible_distribution_release|title }}"
  when: ansible_os_family == 'Debian' and ansible_distribution_release != 'NA'

# ansible_distribution_version is either in format "9.0" or "buster/sid"
- set_fact:
    distribution_codename: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('/')[0]|title }}"
  when: ansible_os_family == 'Debian' and ansible_distribution_release == 'NA' and not ansible_distribution_version is number

- set_fact:
    distribution_codename: "{{ ansible_distribution }}-{{ ansible_distribution_version.split('.')[0] }}"
  when: ansible_os_family == 'Debian' and ansible_distribution_release == 'NA' and ansible_distribution_version is number

- include_vars: "{{ distribution_codename }}.yml"

- set_fact:
    apt_packages: "{{ __apt_packages_stage0|list + __apt_packages_stage1|list }}"

- set_fact:
    debconf_selections: "{{ __debconf_selections|list }}"

- include_tasks: setup-Debian.yml
  when: ansible_os_family == 'Debian'
