---
- apt:
    update_cache: yes
    cache_valid_time: 86400 # 1 day

- name: Satisfy Ansible requirements
  meta: noop
  # Package debconf is required for Ansible's debconf module. It has priority level 'required' and hence it is installed
  # by default on Debian and its derivates. Package debconf-utils is never used although it is listed as a dependency of
  # Ansible's debconf module

- debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: "{{ unattended_upgrades_enable_auto_updates }}"
    vtype: boolean

- debconf:
    name: locales
    question: locales/locales_to_be_generated
    value: "{{ locales_locales_to_be_generated|join(', ') }}"
    vtype: multiselect

- debconf:
    name: locales
    question: locales/default_environment_locale
    value: "{{ locales_default_environment_locale }}"
    vtype: select

- when: distribution_id in [ ['Debian', '10'], ['Debian', '11'] ]
  block:
  - file:
      path: /etc/apt/sources.list
      state: absent

  - copy:
      src: "{{ distribution_id|join('-') }}/"
      dest: /
      mode: preserve

- jm1.pkg.meta_pkg:
    name: "jm1-base-system"
    version: "1"
    depends:
    # NOTE: Sync package list with JM1's install guides for Debian.
    - acl
    - apt-listchanges
    - apt-transport-https
    - aptitude
    - at
    - locales
    - patch
    - p7zip-full
    - sudo
    - xz-utils

#- fzf # Debian 10 (Buster) and later
