---
- apt:
    update_cache: yes

- include_role:
    name: jm1.virtual_pkg
  vars:
    package_name: "jm1-base-system-stage0"
    package_depends:
    # NOTE: Sync package list with JM1's install guides for Debian.
    - dialog
    - libreadline-dev
    - apt-utils
    - kmod
    - inetutils-ping
    - iproute2
    - debconf       # required for
    - debconf-utils # Ansible's debconf module

- debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: "{{ unattended_upgrades_enable_auto_updates }}"
    vtype: boolean

- debconf:
    name: locales
    question: locales/locales_to_be_generated
    value: "{{ locales_locales_to_be_generated|join(', ') }}"
    vtype: multiselect

- debconf:
    name: locales
    question: locales/default_environment_locale
    value: "{{ locales_default_environment_locale }}"
    vtype: select

- file:
    path: /etc/apt/sources.list
    state: absent

- copy:
    src: "{{ ansible_distribution }}-{{ ansible_distribution_version }}/"
    dest: /
    mode: preserve


- include_role:
    name: jm1.virtual_pkg
  vars:
    package_name: "jm1-base-system-stage1"
    package_depends:
    # NOTE: Sync package list with JM1's install guides for Debian.
    - sudo
    - man-db
    - screen
    - vim
    - p7zip-full
    - curl
    - locales
    - locales-all
    - htop
    - bash-completion
    - console-setup
    - keyboard-configuration
    - lshw
    - patch
    - aptitude
    - net-tools
    - fzf
