---
- apt:
    update_cache: yes

- include_role:
    name: jm1.virtual_pkg
  vars:
     package_name: "jm1-base-system-stage0"
     package_depends: "{{ packages_stage0 }}"

- debconf:
    name: unattended-upgrades
    question: unattended-upgrades/enable_auto_updates
    value: "{{ unattended_upgrades_enable_auto_updates }}"
    vtype: boolean

- debconf:
    name: locales
    question: locales/locales_to_be_generated
    value: "{{ locales_locales_to_be_generated|join(', ') }}"
    vtype: multiselect

- debconf:
    name: locales
    question: locales/default_environment_locale
    value: "{{ locales_default_environment_locale }}"
    vtype: select

- file:
    path: /etc/apt/sources.list
    state: absent

- copy:
    src: "{{ ansible_distribution }}-{{ ansible_distribution_version }}/"
    dest: /
    mode: preserve

- include_role:
    name: jm1.virtual_pkg
  vars:
     package_name: "jm1-base-system-stage1"
     package_depends: "{{ packages_stage1 }}"
